version: '2.0'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  server:
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - ./src/:/home/
    env_file:
      - .env
    ports:
      - "127.0.0.1:5000:5000"
    command: python3 app.py

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
      - ./data/pgadmin/data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "127.0.0.1:7000:80"